# SWITCHES
#set_property PACKAGE_PIN V17 [get_ports {c}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {c}]
#set_property PACKAGE_PIN V16 [get_ports {b}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {b}]
#set_property PACKAGE_PIN W16 [get_ports {e}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {e}]

#set_property PACKAGE_PIN V17 [get_ports {c}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {c}]
#set_property PACKAGE_PIN V16 [get_ports {b}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {b}]
#set_property PACKAGE_PIN W16 [get_ports {a}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {a}]

	
# LEDS
#set_property PACKAGE_PIN U16 [get_ports {d0}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {d0}]
#set_property PACKAGE_PIN E19 [get_ports {d1}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {d1}]
#set_property PACKAGE_PIN U19 [get_ports {d2}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {d2}]
#set_property PACKAGE_PIN V19 [get_ports {d3}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {d3}]
#set_property PACKAGE_PIN W15 [get_ports {d4}]					
    #set_property IOSTANDARD LVCMOS33 [get_ports {d4}]
#set_property PACKAGE_PIN V15 [get_ports {d5}]                    
    #set_property IOSTANDARD LVCMOS33 [get_ports {d5}]
#set_property PACKAGE_PIN W14 [get_ports {d6}]                    
    #set_property IOSTANDARD LVCMOS33 [get_ports {d6}]
#set_property PACKAGE_PIN W13 [get_ports {d7}]                    
    #set_property IOSTANDARD LVCMOS33 [get_ports {d7}]
	
set_property PACKAGE_PIN V17 [get_ports {B0}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {B0}]
set_property PACKAGE_PIN V16 [get_ports {B1}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B1}]
set_property PACKAGE_PIN W16 [get_ports {B2}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B2}]
set_property PACKAGE_PIN W17 [get_ports {B3}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {B3}]
set_property PACKAGE_PIN W15 [get_ports {A0}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A0}]
set_property PACKAGE_PIN V15 [get_ports {A1}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A1}]
set_property PACKAGE_PIN W14 [get_ports {A2}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A2}]
set_property PACKAGE_PIN W13 [get_ports {A3}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {A3}]
set_property PACKAGE_PIN V2 [get_ports {C_IN}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {C_IN}]
        
        
 set_property PACKAGE_PIN U16 [get_ports {S0}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {S0}]
 set_property PACKAGE_PIN E19 [get_ports {S1}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {S1}]
 set_property PACKAGE_PIN U19 [get_ports {S2}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {S2}]
 set_property PACKAGE_PIN V19 [get_ports {S3}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {S3}]
 set_property PACKAGE_PIN W18 [get_ports {C_OUT}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {C_OUT}]