# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /nfs/nfs4/home/bmwynne/Documents/fall-2015/b441-submissions/Lab06/Lab06.cache/wt [current_project]
set_property parent.project_path /nfs/nfs4/home/bmwynne/Documents/fall-2015/b441-submissions/Lab06/Lab06.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /nfs/nfs4/home/bmwynne/Documents/fall-2015/b441-submissions/Lab06/Lab06.srcs/sources_1/new/main.v
synth_design -top paradd4 -part xc7a35ticpg236-1L
write_checkpoint -noxdef paradd4.dcp
catch { report_utilization -file paradd4_utilization_synth.rpt -pb paradd4_utilization_synth.pb }
